# Generated by Django 5.2.7 on 2025-11-13 05:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblBuildings',
            fields=[
                ('building_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tbl_buildings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblCollege',
            fields=[
                ('college_id', models.TextField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_college',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblCourse',
            fields=[
                ('course_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblRoles',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField()),
            ],
            options={
                'db_table': 'tbl_roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblTerm',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
                ('term_name', models.TextField()),
            ],
            options={
                'db_table': 'tbl_term',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblUserRoleHistory',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_role_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('college_id', models.TextField(blank=True, null=True)),
                ('department_id', models.TextField(blank=True, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_user_role_history',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblUsers',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email_address', models.CharField(max_length=50, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('avatar_url', models.CharField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('user_uuid', models.UUIDField(blank=True, null=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'tbl_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblAvailableRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=50)),
                ('college_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_available_rooms',
                'managed': True,
                'unique_together': {('room_id', 'college_id')},
            },
        ),
        migrations.CreateModel(
            name='TblDepartment',
            fields=[
                ('department_id', models.TextField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblcollege')),
            ],
            options={
                'db_table': 'tbl_department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblExamperiod',
            fields=[
                ('examperiod_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('academic_year', models.TextField()),
                ('exam_category', models.TextField()),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblcollege')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tbldepartment')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblterm')),
            ],
            options={
                'db_table': 'tbl_examperiod',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblProgram',
            fields=[
                ('program_id', models.TextField(primary_key=True, serialize=False)),
                ('program_name', models.CharField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tbldepartment')),
            ],
            options={
                'db_table': 'tbl_program',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblRooms',
            fields=[
                ('room_id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=500)),
                ('room_type', models.CharField(max_length=500)),
                ('room_capacity', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblbuildings')),
            ],
            options={
                'db_table': 'tbl_rooms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblModality',
            fields=[
                ('modality_id', models.AutoField(primary_key=True, serialize=False)),
                ('modality_type', models.TextField()),
                ('room_type', models.TextField()),
                ('modality_remarks', models.TextField(blank=True, null=True)),
                ('program_id', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('section_name', models.CharField(blank=True, null=True)),
                ('possible_rooms', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblcourse')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblrooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblusers')),
            ],
            options={
                'db_table': 'tbl_modality',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tblcourse',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblterm'),
        ),
        migrations.CreateModel(
            name='TblUserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_ended', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblcollege')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tbldepartment')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblroles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblusers')),
            ],
            options={
                'db_table': 'tbl_user_role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblSectioncourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('number_of_students', models.IntegerField()),
                ('year_level', models.TextField()),
                ('is_night_class', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblcourse')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblprogram')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblterm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblusers')),
            ],
            options={
                'db_table': 'tbl_sectioncourse',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblScheduleapproval',
            fields=[
                ('dean_user_id', models.IntegerField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('request_id', models.UUIDField(primary_key=True, serialize=False)),
                ('schedule_data', models.JSONField(blank=True, null=True)),
                ('college_name', models.TextField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(blank=True, db_column='submitted_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblusers')),
            ],
            options={
                'db_table': 'tbl_scheduleapproval',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('link_url', models.TextField(blank=True, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.SmallIntegerField(default=0)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tblnotification_sender_set', to='api.tblusers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tblusers')),
            ],
            options={
                'db_table': 'tbl_notification',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblExamdetails',
            fields=[
                ('examdetails_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=50)),
                ('program_id', models.TextField()),
                ('exam_duration', models.DurationField(blank=True, null=True)),
                ('exam_start_time', models.DateTimeField(blank=True, null=True)),
                ('exam_end_time', models.DateTimeField(blank=True, null=True)),
                ('proctor_timein', models.DateTimeField(blank=True, null=True)),
                ('proctor_timeout', models.DateTimeField(blank=True, null=True)),
                ('section_name', models.CharField(blank=True, null=True)),
                ('academic_year', models.TextField(blank=True, null=True)),
                ('semester', models.TextField(blank=True, null=True)),
                ('exam_category', models.TextField(blank=True, null=True)),
                ('exam_period', models.TextField(blank=True, null=True)),
                ('exam_date', models.TextField(blank=True, null=True)),
                ('college_name', models.TextField(blank=True, null=True)),
                ('building_name', models.CharField(blank=True, null=True)),
                ('instructor_id', models.IntegerField(blank=True, null=True)),
                ('examperiod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblexamperiod')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblmodality')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblrooms')),
                ('proctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblusers')),
            ],
            options={
                'db_table': 'tbl_examdetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblCourseUsers',
            fields=[
                ('pk', models.CompositePrimaryKey('course_id', 'user_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, null=True)),
                ('is_bayanihan_leader', models.BooleanField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblusers')),
            ],
            options={
                'db_table': 'tbl_course_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblAvailability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
                ('time_slots', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('status', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tblusers')),
            ],
            options={
                'db_table': 'tbl_availability',
                'managed': True,
            },
        ),
    ]
