# Generated by Django 5.2.7 on 2025-11-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tblavailability',
            index=models.Index(fields=['user'], name='tbl_availab_user_id_248afd_idx'),
        ),
        migrations.AddIndex(
            model_name='tblavailability',
            index=models.Index(fields=['status'], name='tbl_availab_status_f98867_idx'),
        ),
        migrations.AddIndex(
            model_name='tblavailablerooms',
            index=models.Index(fields=['room_id'], name='tbl_availab_room_id_55b078_idx'),
        ),
        migrations.AddIndex(
            model_name='tblavailablerooms',
            index=models.Index(fields=['college_id'], name='tbl_availab_college_454daf_idx'),
        ),
        migrations.AddIndex(
            model_name='tblbuildings',
            index=models.Index(fields=['building_name'], name='tbl_buildin_buildin_cc9419_idx'),
        ),
        migrations.AddIndex(
            model_name='tblcourse',
            index=models.Index(fields=['term'], name='tbl_course_term_id_51933a_idx'),
        ),
        migrations.AddIndex(
            model_name='tblcourseusers',
            index=models.Index(fields=['course'], name='tbl_course__course__dd15bb_idx'),
        ),
        migrations.AddIndex(
            model_name='tblcourseusers',
            index=models.Index(fields=['user'], name='tbl_course__user_id_aeff86_idx'),
        ),
        migrations.AddIndex(
            model_name='tbldepartment',
            index=models.Index(fields=['college'], name='tbl_departm_college_755cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='tbldepartment',
            index=models.Index(fields=['department_name'], name='tbl_departm_departm_3b82e2_idx'),
        ),
        migrations.AddIndex(
            model_name='tblexamdetails',
            index=models.Index(fields=['room'], name='tbl_examdet_room_id_f26784_idx'),
        ),
        migrations.AddIndex(
            model_name='tblexamdetails',
            index=models.Index(fields=['modality'], name='tbl_examdet_modalit_2a0ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='tblexamdetails',
            index=models.Index(fields=['proctor'], name='tbl_examdet_proctor_17378d_idx'),
        ),
        migrations.AddIndex(
            model_name='tblexamdetails',
            index=models.Index(fields=['examperiod'], name='tbl_examdet_examper_673622_idx'),
        ),
        migrations.AddIndex(
            model_name='tblexamdetails',
            index=models.Index(fields=['exam_date'], name='tbl_examdet_exam_da_e69557_idx'),
        ),
        migrations.AddIndex(
            model_name='tblexamdetails',
            index=models.Index(fields=['course_id'], name='tbl_examdet_course__f6f770_idx'),
        ),
        migrations.AddIndex(
            model_name='tblexamperiod',
            index=models.Index(fields=['start_date'], name='tbl_examper_start_d_541ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='tblexamperiod',
            index=models.Index(fields=['term'], name='tbl_examper_term_id_d967dc_idx'),
        ),
        migrations.AddIndex(
            model_name='tblexamperiod',
            index=models.Index(fields=['college'], name='tbl_examper_college_94ff87_idx'),
        ),
        migrations.AddIndex(
            model_name='tblexamperiod',
            index=models.Index(fields=['department'], name='tbl_examper_departm_45eb62_idx'),
        ),
        migrations.AddIndex(
            model_name='tblmodality',
            index=models.Index(fields=['course'], name='tbl_modalit_course__889953_idx'),
        ),
        migrations.AddIndex(
            model_name='tblmodality',
            index=models.Index(fields=['user'], name='tbl_modalit_user_id_177e39_idx'),
        ),
        migrations.AddIndex(
            model_name='tblmodality',
            index=models.Index(fields=['room'], name='tbl_modalit_room_id_40d0df_idx'),
        ),
        migrations.AddIndex(
            model_name='tblmodality',
            index=models.Index(fields=['program_id'], name='tbl_modalit_program_d67817_idx'),
        ),
        migrations.AddIndex(
            model_name='tblnotification',
            index=models.Index(fields=['user', '-created_at'], name='tbl_notific_user_id_237f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='tblnotification',
            index=models.Index(fields=['is_seen'], name='tbl_notific_is_seen_6a02c0_idx'),
        ),
        migrations.AddIndex(
            model_name='tblnotification',
            index=models.Index(fields=['status'], name='tbl_notific_status_c37736_idx'),
        ),
        migrations.AddIndex(
            model_name='tblprogram',
            index=models.Index(fields=['department'], name='tbl_program_departm_0dbcf0_idx'),
        ),
        migrations.AddIndex(
            model_name='tblprogram',
            index=models.Index(fields=['program_name'], name='tbl_program_program_ebe2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='tblrooms',
            index=models.Index(fields=['building'], name='tbl_rooms_buildin_96f9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='tblrooms',
            index=models.Index(fields=['room_type'], name='tbl_rooms_room_ty_fadc92_idx'),
        ),
        migrations.AddIndex(
            model_name='tblrooms',
            index=models.Index(fields=['room_name'], name='tbl_rooms_room_na_3be872_idx'),
        ),
        migrations.AddIndex(
            model_name='tblsectioncourse',
            index=models.Index(fields=['course'], name='tbl_section_course__4338dd_idx'),
        ),
        migrations.AddIndex(
            model_name='tblsectioncourse',
            index=models.Index(fields=['program'], name='tbl_section_program_e2c484_idx'),
        ),
        migrations.AddIndex(
            model_name='tblsectioncourse',
            index=models.Index(fields=['term'], name='tbl_section_term_id_f00079_idx'),
        ),
        migrations.AddIndex(
            model_name='tblsectioncourse',
            index=models.Index(fields=['user'], name='tbl_section_user_id_61b6c1_idx'),
        ),
        migrations.AddIndex(
            model_name='tbluserrole',
            index=models.Index(fields=['user'], name='tbl_user_ro_user_id_0e2944_idx'),
        ),
        migrations.AddIndex(
            model_name='tbluserrole',
            index=models.Index(fields=['role'], name='tbl_user_ro_role_id_ea8668_idx'),
        ),
        migrations.AddIndex(
            model_name='tbluserrole',
            index=models.Index(fields=['college'], name='tbl_user_ro_college_3a43c2_idx'),
        ),
        migrations.AddIndex(
            model_name='tbluserrole',
            index=models.Index(fields=['status'], name='tbl_user_ro_status_201146_idx'),
        ),
        migrations.AddIndex(
            model_name='tblusers',
            index=models.Index(fields=['email_address'], name='tbl_users_email_a_18f576_idx'),
        ),
        migrations.AddIndex(
            model_name='tblusers',
            index=models.Index(fields=['status'], name='tbl_users_status_d8da20_idx'),
        ),
    ]
