# Generated by Django 5.2.7 on 2025-11-16 20:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tblavailability_tbl_availab_user_id_248afd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tblmodality',
            name='tbl_modalit_course__889953_idx',
        ),
        migrations.RemoveIndex(
            model_name='tblmodality',
            name='tbl_modalit_user_id_177e39_idx',
        ),
        migrations.RemoveIndex(
            model_name='tblmodality',
            name='tbl_modalit_room_id_40d0df_idx',
        ),
        migrations.RemoveIndex(
            model_name='tblmodality',
            name='tbl_modalit_program_d67817_idx',
        ),
        migrations.AlterField(
            model_name='tblmodality',
            name='possible_rooms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None),
        ),
    ]
