# Generated by Django 5.2.7 on 2025-11-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_tblmodality_tbl_modalit_course__889953_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tblexamdetails',
            unique_together={('modality', 'exam_date', 'exam_start_time')},
        ),
    ]
