# Generated by Django 5.2.7 on 2025-11-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tblexamdetails_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tblexamdetails',
            index=models.Index(fields=['college_name'], name='tbl_examdet_college_599539_idx'),
        ),
    ]
