# Generated by Django 5.2.7 on 2025-11-30 10:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tblexamdetails_tbl_examdet_college_599539_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblmodality',
            name='section_name',
        ),
        migrations.AddField(
            model_name='tblmodality',
            name='sections',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None),
        ),
    ]
