# Generated by Django 5.2.7 on 2025-12-01 02:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_tblmodality_section_name_tblmodality_sections'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tblexamdetails',
            name='tbl_examdet_room_id_f26784_idx',
        ),
        migrations.RemoveIndex(
            model_name='tblexamdetails',
            name='tbl_examdet_modalit_2a0ebb_idx',
        ),
        migrations.RemoveIndex(
            model_name='tblexamdetails',
            name='tbl_examdet_proctor_17378d_idx',
        ),
        migrations.RemoveIndex(
            model_name='tblexamdetails',
            name='tbl_examdet_examper_673622_idx',
        ),
        migrations.RemoveIndex(
            model_name='tblexamdetails',
            name='tbl_examdet_exam_da_e69557_idx',
        ),
        migrations.RemoveIndex(
            model_name='tblexamdetails',
            name='tbl_examdet_course__f6f770_idx',
        ),
        migrations.RemoveIndex(
            model_name='tblexamdetails',
            name='tbl_examdet_college_599539_idx',
        ),
        migrations.AlterUniqueTogether(
            name='tblexamdetails',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tblexamdetails',
            name='section_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None),
        ),
    ]
