# Generated by Django 5.2.7 on 2025-10-30 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_tblroles_options_alter_tbluserrole_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluserrole',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblcollege'),
        ),
        migrations.AddField(
            model_name='tbluserrole',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tbldepartment'),
        ),
        migrations.AddField(
            model_name='tbluserrole',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblroles'),
        ),
        migrations.AddField(
            model_name='tbluserrole',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblusers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblroles',
            name='role_name',
            field=models.CharField(max_length=255),
        ),
    ]
