# Generated by Django 5.2.7 on 2025-12-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_tblexamdetails_tbl_examdet_room_id_f26784_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblexamdetails',
            name='section_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tblexamdetails',
            unique_together={('modality', 'exam_date', 'exam_start_time')},
        ),
        migrations.AddIndex(
            model_name='tblexamdetails',
            index=models.Index(fields=['room'], name='tbl_examdet_room_id_f26784_idx'),
        ),
        migrations.AddIndex(
            model_name='tblexamdetails',
            index=models.Index(fields=['modality'], name='tbl_examdet_modalit_2a0ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='tblexamdetails',
            index=models.Index(fields=['proctor'], name='tbl_examdet_proctor_17378d_idx'),
        ),
        migrations.AddIndex(
            model_name='tblexamdetails',
            index=models.Index(fields=['examperiod'], name='tbl_examdet_examper_673622_idx'),
        ),
        migrations.AddIndex(
            model_name='tblexamdetails',
            index=models.Index(fields=['exam_date'], name='tbl_examdet_exam_da_e69557_idx'),
        ),
        migrations.AddIndex(
            model_name='tblexamdetails',
            index=models.Index(fields=['course_id'], name='tbl_examdet_course__f6f770_idx'),
        ),
        migrations.AddIndex(
            model_name='tblexamdetails',
            index=models.Index(fields=['college_name'], name='tbl_examdet_college_599539_idx'),
        ),
    ]
