# Generated by Django 5.2.7 on 2025-12-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_tblexamdetails_section_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tblexamdetails',
            name='tbl_examdet_college_599539_idx',
        ),
        migrations.RemoveField(
            model_name='tblmodality',
            name='sections',
        ),
        migrations.AddField(
            model_name='tblmodality',
            name='section_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
