# Generated by Django 5.2.7 on 2025-10-31 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_tbluserrole_college_tbluserrole_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblsectioncourse',
            options={'managed': True},
        ),
    ]
