# Generated by Django 5.2.7 on 2025-12-01 05:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_tblexamdetails_tbl_examdet_college_599539_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tblexamdetails',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tblmodality',
            name='section_name',
        ),
        migrations.AddField(
            model_name='tblexamdetails',
            name='instructors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='tblexamdetails',
            name='proctors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='tblexamdetails',
            name='sections',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='tblmodality',
            name='sections',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='tblmodality',
            name='total_students',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
