# Generated by Django 5.2.7 on 2025-10-31 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_tblsectioncourse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsectioncourse',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblcourse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblsectioncourse',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblprogram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblsectioncourse',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblterm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblsectioncourse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblusers'),
        ),
        migrations.AlterField(
            model_name='tblsectioncourse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
