# Generated by Django 5.2.7 on 2025-12-01 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_tblexamdetails_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblExamOtp',
            fields=[
                ('otp_id', models.AutoField(primary_key=True, serialize=False)),
                ('otp_code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('examdetails', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_record', to='api.tblexamdetails')),
            ],
            options={
                'db_table': 'tbl_exam_otp',
                'managed': True,
                'indexes': [models.Index(fields=['otp_code'], name='tbl_exam_ot_otp_cod_33567f_idx'), models.Index(fields=['examdetails'], name='tbl_exam_ot_examdet_6e2d8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TblProctorAttendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_substitute', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('otp_used', models.CharField(max_length=50)),
                ('examdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.tblexamdetails')),
                ('proctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_attendances', to='api.tblusers')),
            ],
            options={
                'db_table': 'tbl_proctor_attendance',
                'managed': True,
                'indexes': [models.Index(fields=['examdetails'], name='tbl_proctor_examdet_169de0_idx'), models.Index(fields=['proctor'], name='tbl_proctor_proctor_4b179d_idx'), models.Index(fields=['time_in'], name='tbl_proctor_time_in_f91d5a_idx')],
                'unique_together': {('examdetails', 'proctor')},
            },
        ),
        migrations.CreateModel(
            name='TblProctorSubstitution',
            fields=[
                ('substitution_id', models.AutoField(primary_key=True, serialize=False)),
                ('justification', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('examdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='api.tblexamdetails')),
                ('original_proctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_as_original', to='api.tblusers')),
                ('substitute_proctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_as_substitute', to='api.tblusers')),
            ],
            options={
                'db_table': 'tbl_proctor_substitution',
                'managed': True,
                'indexes': [models.Index(fields=['examdetails'], name='tbl_proctor_examdet_d77718_idx'), models.Index(fields=['created_at'], name='tbl_proctor_created_45333e_idx')],
            },
        ),
    ]
