# Generated by Django 5.2.7 on 2025-12-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tblexamotp_tblproctorattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblexamdetails',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('late', 'Late'), ('absent', 'Absent'), ('substitute', 'Substitute')], default='pending', max_length=20, null=True),
        ),
    ]
