# Generated by Django 5.2.7 on 2025-12-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tblexamdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblusers',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full-time', 'Full-time'), ('part-time', 'Part-time')], help_text='Employment status: full-time or part-time', max_length=20, null=True),
        ),
    ]
