# Generated by Django 5.2.7 on 2025-12-09 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tblusers_employment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblScheduleFooter',
            fields=[
                ('footer_id', models.AutoField(primary_key=True, serialize=False)),
                ('prepared_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prepared_by_title', models.CharField(default='Dean, CITC', max_length=255)),
                ('approved_by_name', models.CharField(default='Type name', max_length=255)),
                ('approved_by_title', models.CharField(default='VCAA, USTP-CDO', max_length=255)),
                ('address_line', models.TextField(default='C.M Recto Avenue, Lapasan, Cagayan de Oro City 9000 Philippines')),
                ('contact_line', models.TextField(default='Tel Nos. +63 (88) 856 1738; Telefax +63 (88) 856 4696 | http://www.ustp.edu.ph')),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblcollege')),
            ],
            options={
                'db_table': 'tbl_schedule_footer',
                'managed': True,
                'indexes': [models.Index(fields=['college'], name='tbl_schedul_college_cc26eb_idx')],
            },
        ),
    ]
