# Generated by Django 5.2.7 on 2025-12-14 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_tblschedulefooter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblexamdetails',
            name='proctor_timein',
        ),
        migrations.RemoveField(
            model_name='tblexamdetails',
            name='proctor_timeout',
        ),
        migrations.RemoveField(
            model_name='tblexamdetails',
            name='status',
        ),
    ]
