# Generated by Django 5.2.7 on 2025-12-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_tblexamdetails_proctor_timein_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblProctorAttendanceHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_id', models.IntegerField()),
                ('examdetails_id', models.IntegerField()),
                ('proctor_id', models.IntegerField()),
                ('proctor_name', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=50)),
                ('section_name', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_date', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_start_time', models.DateTimeField(blank=True, null=True)),
                ('exam_end_time', models.DateTimeField(blank=True, null=True)),
                ('building_name', models.CharField(blank=True, max_length=255, null=True)),
                ('room_id', models.CharField(blank=True, max_length=50, null=True)),
                ('instructor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_substitute', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('otp_used', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_proctor_attendance_history',
                'managed': True,
                'indexes': [models.Index(fields=['proctor_id'], name='tbl_proctor_proctor_5cc913_idx'), models.Index(fields=['exam_date'], name='tbl_proctor_exam_da_9432d7_idx'), models.Index(fields=['archived_at'], name='tbl_proctor_archive_756972_idx')],
            },
        ),
    ]
