# Generated by Django 5.2.7 on 2025-12-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_tblproctorattendancehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblproctorattendancehistory',
            name='substituted_for_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblproctorattendancehistory',
            name='substituted_for_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
