# Generated by Django 5.2 on 2026-03-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_add_change_request_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tblavailability',
            new_name='tbl_availab_type_0fabe7_idx',
            old_name='tbl_availab_type_idx',
        ),
        migrations.RenameIndex(
            model_name='tblavailability',
            new_name='tbl_availab_type_f0f206_idx',
            old_name='tbl_availab_type_stat_idx',
        ),
    ]
